// <auto-generated />
using System;
using System.Collections.Generic;
using BRB.Core.Common.Models;
using Core.Brokers.DbContext;
using Core.Entities.Course;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128113435_CreateTableNotification")]
    partial class CreateTableNotification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("UserNormGeneralSequence");

            modelBuilder.Entity("Core.Entities.Auth.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text")
                        .HasColumnName("fcm_token");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("Key")
                        .HasDatabaseName("ix_devices_key");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_devices_user_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Auth.SignLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("SignAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sign_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sign_logs");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_sign_logs_device_id");

                    b.HasIndex("SignAt")
                        .HasDatabaseName("ix_sign_logs_sign_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sign_logs_user_id");

                    b.ToTable("sign_logs", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Auth.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("password");

                    b.Property<string>("RToken")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("r_token");

                    b.Property<DateTime>("RTokenExpireAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("r_token_expire_at");

                    b.Property<List<string>>("Roles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("roles");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Auth.UserDaily", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<int>("Metric")
                        .HasColumnType("integer")
                        .HasColumnName("metric");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_user_dailies");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_user_dailies_date");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_dailies_user_id");

                    b.ToTable("user_dailies", (string)null);

                    b.HasDiscriminator().HasValue("UserDaily");
                });

            modelBuilder.Entity("Core.Entities.Auth.UserExtra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("activity_level");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("birth_date");

                    b.Property<double>("Bmi")
                        .HasColumnType("double precision")
                        .HasColumnName("bmi");

                    b.Property<double>("EntryWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("entry_weight");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<double>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("height");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .HasColumnType("text")
                        .HasColumnName("photo");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_user_extras");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_user_extras_name");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_extras_user_id");

                    b.ToTable("user_extras", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Auth.UserNormByMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Menu")
                        .HasColumnType("integer")
                        .HasColumnName("menu");

                    b.Property<int>("Metric")
                        .HasColumnType("integer")
                        .HasColumnName("metric");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_user_norm_by_menus");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_norm_by_menus_user_id");

                    b.ToTable("user_norm_by_menus", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Auth.UserNormGeneral", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"UserNormGeneralSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("Id"));

                    b.Property<int>("Metric")
                        .HasColumnType("integer")
                        .HasColumnName("metric");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_user_norms");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_norms_user_id");

                    b.ToTable("user_norms", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.Auth.UserStepStat", b =>
                {
                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<double>("Sum")
                        .HasColumnType("double precision")
                        .HasColumnName("sum");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_step_stats_user_id");

                    b.ToTable("user_step_stats", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course.Computation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ComputationType")
                        .HasColumnType("integer")
                        .HasColumnName("computation_type");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_computations");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_computations_entity_id");

                    b.ToTable("computations", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Asset[]>("Assets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("assets");

                    b.Property<MultiLanguageField>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<MultiLanguageField>("Info")
                        .HasColumnType("jsonb")
                        .HasColumnName("info");

                    b.Property<decimal>("Order")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("order");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<MultiLanguageField>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("jsonb")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_courses_order");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course.CourseItemState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_course_item_states");

                    b.HasIndex("UserId", "EntityId", "Type")
                        .HasDatabaseName("ix_course_item_states_user_id_entity_id_type");

                    b.ToTable("course_item_states", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Asset[]>("Assets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("assets");

                    b.Property<MultiLanguageField>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<decimal>("Order")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("order");

                    b.Property<MultiLanguageField>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("jsonb")
                        .HasColumnName("title");

                    b.Property<long>("WorkoutId")
                        .HasColumnType("bigint")
                        .HasColumnName("workout_id");

                    b.HasKey("Id")
                        .HasName("pk_exercises");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_exercises_order");

                    b.HasIndex("WorkoutId")
                        .HasDatabaseName("ix_exercises_workout_id");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course.ExerciseMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint")
                        .HasColumnName("exercise_id");

                    b.Property<int>("Metric")
                        .HasColumnType("integer")
                        .HasColumnName("metric");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_exercise_metrics");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_exercise_metrics_exercise_id");

                    b.ToTable("exercise_metrics", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course.Lesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Asset[]>("Assets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("assets");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<MultiLanguageField>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean")
                        .HasColumnName("is_free");

                    b.Property<decimal>("Order")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("order");

                    b.Property<MultiLanguageField>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("jsonb")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_lessons_course_id");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_lessons_order");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course.Workout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Asset[]>("Assets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("assets");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<MultiLanguageField>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<bool>("HasRest")
                        .HasColumnType("boolean")
                        .HasColumnName("has_rest");

                    b.Property<decimal>("Order")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("order");

                    b.Property<MultiLanguageField>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("jsonb")
                        .HasColumnName("title");

                    b.Property<long>("Type")
                        .HasColumnType("bigint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_workouts");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_workouts_course_id");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_workouts_order");

                    b.ToTable("workouts", (string)null);
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.DailyMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint")
                        .HasColumnName("food_id");

                    b.Property<int>("Menu")
                        .HasColumnType("integer")
                        .HasColumnName("menu");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_daily_menus");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("ix_daily_menus_food_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_daily_menus_user_id");

                    b.ToTable("daily_menus", (string)null);
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.Food", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<MultiLanguageField>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_foods");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_foods_category_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_foods_user_id");

                    b.ToTable("foods", (string)null);
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.FoodCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<MultiLanguageField>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_food_categories");

                    b.ToTable("food_categories", (string)null);
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.FoodMetrics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint")
                        .HasColumnName("food_id");

                    b.Property<int>("Metric")
                        .HasColumnType("integer")
                        .HasColumnName("metric");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_food_metrics");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("ix_food_metrics_food_id");

                    b.ToTable("food_metrics", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Notification.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("HasRead")
                        .HasColumnType("boolean")
                        .HasColumnName("has_read");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Notification.Reminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Menu")
                        .HasColumnType("integer")
                        .HasColumnName("menu");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reminders");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reminders_user_id");

                    b.ToTable("reminders", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Refs.Purpose", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<MultiLanguageField>("GroupName")
                        .HasColumnType("jsonb")
                        .HasColumnName("group_name");

                    b.Property<bool>("IsSystemDefined")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_defined");

                    b.HasKey("Id")
                        .HasName("pk_purposes");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_purposes_id");

                    b.ToTable("purposes", (string)null);
                });

            modelBuilder.Entity("FoodUserExtra", b =>
                {
                    b.Property<long>("FavouriteFoodsId")
                        .HasColumnType("bigint")
                        .HasColumnName("favourite_foods_id");

                    b.Property<long>("UserExtraId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_extra_id");

                    b.HasKey("FavouriteFoodsId", "UserExtraId")
                        .HasName("pk_food_user_extra");

                    b.HasIndex("UserExtraId")
                        .HasDatabaseName("ix_food_user_extra_user_extra_id");

                    b.ToTable("food_user_extra", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Auth.Device", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Auth.UserDaily", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_dailies_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Auth.UserExtra", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithOne("Extra")
                        .HasForeignKey("Core.Entities.Auth.UserExtra", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_extras_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Auth.UserNormByMenu", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_norm_by_menus_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Auth.UserNormGeneral", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_norms_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Auth.UserStepStat", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_step_stats_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Course.Exercise", b =>
                {
                    b.HasOne("Core.Entities.Course.Workout", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercises_workouts_workout_id");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Core.Entities.Course.ExerciseMetric", b =>
                {
                    b.HasOne("Core.Entities.Course.Exercise", "Exercise")
                        .WithMany("Metrics")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_metrics_exercises_exercise_id");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Core.Entities.Course.Lesson", b =>
                {
                    b.HasOne("Core.Entities.Course.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Core.Entities.Course.Workout", b =>
                {
                    b.HasOne("Core.Entities.Course.Course", "Course")
                        .WithMany("Workouts")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workouts_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.DailyMenu", b =>
                {
                    b.HasOne("Core.Entities.FoodEntites.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_menus_foods_food_id");

                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_menus_users_user_id");

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.Food", b =>
                {
                    b.HasOne("Core.Entities.FoodEntites.FoodCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_foods_food_categories_category_id");

                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_foods_users_user_id");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.FoodMetrics", b =>
                {
                    b.HasOne("Core.Entities.FoodEntites.Food", "Food")
                        .WithMany("Metrics")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_food_metrics_foods_food_id");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Core.Entities.Notification.Notification", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Notification.Reminder", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reminders_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodUserExtra", b =>
                {
                    b.HasOne("Core.Entities.FoodEntites.Food", null)
                        .WithMany()
                        .HasForeignKey("FavouriteFoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_food_user_extra_foods_favourite_foods_id");

                    b.HasOne("Core.Entities.Auth.UserExtra", null)
                        .WithMany()
                        .HasForeignKey("UserExtraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_food_user_extra_user_extras_user_extra_id");
                });

            modelBuilder.Entity("Core.Entities.Auth.User", b =>
                {
                    b.Navigation("Extra");
                });

            modelBuilder.Entity("Core.Entities.Course.Course", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("Core.Entities.Course.Exercise", b =>
                {
                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("Core.Entities.Course.Workout", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.Food", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
