// <auto-generated />
using System;
using System.Collections.Generic;
using BRB.Core.Common.Models;
using Core.Brokers.DbContext;
using Core.Entities.Course;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204182644_AlterTableDeviceAddColumnIsActive")]
    partial class AlterTableDeviceAddColumnIsActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("UserNormGeneralSequence");

            modelBuilder.Entity("Core.Entities.Auth.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text")
                        .HasColumnName("fcm_token");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("Key")
                        .HasDatabaseName("ix_devices_key");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_devices_user_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Auth.SignLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("SignAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sign_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sign_logs");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_sign_logs_device_id");

                    b.HasIndex("SignAt")
                        .HasDatabaseName("ix_sign_logs_sign_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sign_logs_user_id");

                    b.ToTable("sign_logs", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Auth.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("RToken")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("r_token");

                    b.Property<DateTime>("RTokenExpireAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("r_token_expire_at");

                    b.Property<List<string>>("Roles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("roles");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Auth.UserDaily", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<int>("Metric")
                        .HasColumnType("integer")
                        .HasColumnName("metric");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_user_dailies");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_user_dailies_date");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_dailies_user_id");

                    b.ToTable("user_dailies", (string)null);

                    b.HasDiscriminator().HasValue("UserDaily");
                });

            modelBuilder.Entity("Core.Entities.Auth.UserExtra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("activity_level");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("birth_date");

                    b.Property<double>("Bmi")
                        .HasColumnType("double precision")
                        .HasColumnName("bmi");

                    b.Property<double>("EntryWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("entry_weight");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<double>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("height");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .HasColumnType("text")
                        .HasColumnName("photo");

                    b.Property<int?>("PhysicalActivity")
                        .HasColumnType("integer")
                        .HasColumnName("physical_activity");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_user_extras");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_user_extras_name");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_extras_user_id");

                    b.ToTable("user_extras", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Auth.UserNormByMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Menu")
                        .HasColumnType("integer")
                        .HasColumnName("menu");

                    b.Property<int>("Metric")
                        .HasColumnType("integer")
                        .HasColumnName("metric");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_user_norm_by_menus");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_norm_by_menus_user_id");

                    b.ToTable("user_norm_by_menus", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Auth.UserNormGeneral", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"UserNormGeneralSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("Id"));

                    b.Property<int>("Metric")
                        .HasColumnType("integer")
                        .HasColumnName("metric");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_user_norms");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_norms_user_id");

                    b.ToTable("user_norms", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.Auth.UserStepStat", b =>
                {
                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<double>("Sum")
                        .HasColumnType("double precision")
                        .HasColumnName("sum");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_step_stats_user_id");

                    b.ToTable("user_step_stats", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Billing.ClickTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("CardToken")
                        .HasColumnType("text")
                        .HasColumnName("card_token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<long>("Delivery")
                        .HasColumnType("bigint")
                        .HasColumnName("delivery");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("text")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("PaymentId")
                        .HasColumnType("text")
                        .HasColumnName("payment_id");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<long>("Tax")
                        .HasColumnType("bigint")
                        .HasColumnName("tax");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_click_transactions");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_click_transactions_order_id");

                    b.ToTable("click_transactions", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Billing.Coupon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<List<long>>("AllowedUserIds")
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_user_ids");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expire_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("OneTime")
                        .HasColumnType("boolean")
                        .HasColumnName("one_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Usages")
                        .HasColumnType("integer")
                        .HasColumnName("usages");

                    b.HasKey("Id")
                        .HasName("pk_coupons");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_coupons_code");

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Billing.CouponUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("CouponId")
                        .HasColumnType("bigint")
                        .HasColumnName("coupon_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_coupon_usages");

                    b.HasIndex("CouponId", "UserId", "OrderId")
                        .HasDatabaseName("ix_coupon_usages_coupon_id_user_id_order_id");

                    b.ToTable("coupon_usages", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Billing.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long?>("CouponId")
                        .HasColumnType("bigint")
                        .HasColumnName("coupon_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CouponId")
                        .HasDatabaseName("ix_orders_coupon_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orders_status");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_orders_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orders_user_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Billing.Payme.PaymeTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExternalCreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("external_created_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("external_id");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("PerformedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("performed_at");

                    b.Property<int?>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payme_transactions");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_payme_transactions_external_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_payme_transactions_order_id");

                    b.ToTable("payme_transactions", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Billing.PlanExtra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("integer")
                        .HasColumnName("duration_in_months");

                    b.Property<long>("Fee")
                        .HasColumnType("bigint")
                        .HasColumnName("fee");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Plan")
                        .HasColumnType("integer")
                        .HasColumnName("plan");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_plan_extras");

                    b.HasIndex("Plan")
                        .HasDatabaseName("ix_plan_extras_plan");

                    b.ToTable("plan_extras", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Billing.PlanFeature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature_key");

                    b.Property<string>("Limit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("limit");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_plan_features");

                    b.HasIndex("PlanId", "FeatureKey")
                        .IsUnique()
                        .HasDatabaseName("ix_plan_features_plan_id_feature_key");

                    b.ToTable("plan_features", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Billing.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ends_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("starts_at");

                    b.Property<int>("SubscriptionPlan")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_plan");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("SubscriptionPlan")
                        .HasDatabaseName("ix_subscriptions_subscription_plan");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_user_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Billing.SubscriptionOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<int>("Plan")
                        .HasColumnType("integer")
                        .HasColumnName("plan");

                    b.Property<long>("PlanExtraId")
                        .HasColumnType("bigint")
                        .HasColumnName("plan_extra_id");

                    b.HasKey("Id")
                        .HasName("pk_subscription_orders");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_subscription_orders_order_id");

                    b.HasIndex("PlanExtraId")
                        .HasDatabaseName("ix_subscription_orders_plan_extra_id");

                    b.ToTable("subscription_orders", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course.Computation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ComputationType")
                        .HasColumnType("integer")
                        .HasColumnName("computation_type");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_computations");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_computations_entity_id");

                    b.ToTable("computations", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Asset[]>("Assets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("assets");

                    b.Property<MultiLanguageField>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<MultiLanguageField>("Info")
                        .HasColumnType("jsonb")
                        .HasColumnName("info");

                    b.Property<decimal>("Order")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("order");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<MultiLanguageField>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("jsonb")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_courses_order");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course.CourseItemState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_course_item_states");

                    b.HasIndex("UserId", "EntityId", "Type")
                        .HasDatabaseName("ix_course_item_states_user_id_entity_id_type");

                    b.ToTable("course_item_states", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Asset[]>("Assets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("assets");

                    b.Property<MultiLanguageField>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<decimal>("Order")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("order");

                    b.Property<MultiLanguageField>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("jsonb")
                        .HasColumnName("title");

                    b.Property<long>("WorkoutId")
                        .HasColumnType("bigint")
                        .HasColumnName("workout_id");

                    b.HasKey("Id")
                        .HasName("pk_exercises");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_exercises_order");

                    b.HasIndex("WorkoutId")
                        .HasDatabaseName("ix_exercises_workout_id");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course.ExerciseMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint")
                        .HasColumnName("exercise_id");

                    b.Property<int>("Metric")
                        .HasColumnType("integer")
                        .HasColumnName("metric");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_exercise_metrics");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_exercise_metrics_exercise_id");

                    b.ToTable("exercise_metrics", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course.Lesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Asset[]>("Assets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("assets");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<MultiLanguageField>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean")
                        .HasColumnName("is_free");

                    b.Property<decimal>("Order")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("order");

                    b.Property<MultiLanguageField>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("jsonb")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_lessons_course_id");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_lessons_order");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course.Workout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Asset[]>("Assets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("assets");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<MultiLanguageField>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<bool>("HasRest")
                        .HasColumnType("boolean")
                        .HasColumnName("has_rest");

                    b.Property<decimal>("Order")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("order");

                    b.Property<MultiLanguageField>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("jsonb")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_workouts");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_workouts_course_id");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_workouts_order");

                    b.ToTable("workouts", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course.WorkoutComputationIndex", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("TotalCounts")
                        .HasColumnType("integer")
                        .HasColumnName("total_counts");

                    b.Property<TimeSpan>("TotalDuration")
                        .HasColumnType("interval")
                        .HasColumnName("total_duration");

                    b.HasKey("Id")
                        .HasName("pk_workout_computation_indices");

                    b.HasIndex("EntityId", "Level")
                        .HasDatabaseName("ix_workout_computation_indices_entity_id_level");

                    b.ToTable("workout_computation_indices", (string)null);
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.DailyMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint")
                        .HasColumnName("food_id");

                    b.Property<int>("Menu")
                        .HasColumnType("integer")
                        .HasColumnName("menu");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_daily_menus");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("ix_daily_menus_food_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_daily_menus_user_id");

                    b.ToTable("daily_menus", (string)null);
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.Food", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<MultiLanguageField>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_foods");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_foods_category_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_foods_user_id");

                    b.ToTable("foods", (string)null);
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.FoodCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<MultiLanguageField>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_food_categories");

                    b.ToTable("food_categories", (string)null);
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.FoodMetrics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint")
                        .HasColumnName("food_id");

                    b.Property<int>("Metric")
                        .HasColumnType("integer")
                        .HasColumnName("metric");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_food_metrics");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("ix_food_metrics_food_id");

                    b.ToTable("food_metrics", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Notification.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("discriminator");

                    b.Property<bool>("HasRead")
                        .HasColumnType("boolean")
                        .HasColumnName("has_read");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Notification");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.Notification.Reminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Menu")
                        .HasColumnType("integer")
                        .HasColumnName("menu");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval")
                        .HasColumnName("time");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reminders");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reminders_user_id");

                    b.ToTable("reminders", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Notification.ReminderMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int?>("Menu")
                        .HasColumnType("integer")
                        .HasColumnName("menu");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_reminder_messages");

                    b.ToTable("reminder_messages", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Refs.Purpose", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<MultiLanguageField>("GroupName")
                        .HasColumnType("jsonb")
                        .HasColumnName("group_name");

                    b.Property<bool>("IsSystemDefined")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_defined");

                    b.HasKey("Id")
                        .HasName("pk_purposes");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_purposes_id");

                    b.ToTable("purposes", (string)null);
                });

            modelBuilder.Entity("FoodUserExtra", b =>
                {
                    b.Property<long>("FavouriteFoodsId")
                        .HasColumnType("bigint")
                        .HasColumnName("favourite_foods_id");

                    b.Property<long>("UserExtraId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_extra_id");

                    b.HasKey("FavouriteFoodsId", "UserExtraId")
                        .HasName("pk_food_user_extra");

                    b.HasIndex("UserExtraId")
                        .HasDatabaseName("ix_food_user_extra_user_extra_id");

                    b.ToTable("food_user_extra", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Notification.PushNotification", b =>
                {
                    b.HasBaseType("Core.Entities.Notification.Notification");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("failure_count");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<Dictionary<string, string>>("Meta")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta");

                    b.Property<DateTime?>("Scheduled")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scheduled");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("success_count");

                    b.HasDiscriminator().HasValue("PushNotification");
                });

            modelBuilder.Entity("Core.Entities.Auth.Device", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Auth.UserDaily", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_dailies_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Auth.UserExtra", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithOne("Extra")
                        .HasForeignKey("Core.Entities.Auth.UserExtra", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_extras_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Auth.UserNormByMenu", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_norm_by_menus_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Auth.UserNormGeneral", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_norms_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Auth.UserStepStat", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_step_stats_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Billing.ClickTransaction", b =>
                {
                    b.HasOne("Core.Entities.Billing.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_click_transactions_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Core.Entities.Billing.Order", b =>
                {
                    b.HasOne("Core.Entities.Billing.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .HasConstraintName("fk_orders_coupons_coupon_id");

                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_users_user_id");

                    b.Navigation("Coupon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Billing.Payme.PaymeTransaction", b =>
                {
                    b.HasOne("Core.Entities.Billing.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payme_transactions_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Core.Entities.Billing.PlanFeature", b =>
                {
                    b.HasOne("Core.Entities.Billing.PlanExtra", "PlanExtra")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_features_plan_extras_plan_id");

                    b.Navigation("PlanExtra");
                });

            modelBuilder.Entity("Core.Entities.Billing.Subscription", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("Core.Entities.Billing.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Billing.SubscriptionOrder", b =>
                {
                    b.HasOne("Core.Entities.Billing.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_orders_orders_order_id");

                    b.HasOne("Core.Entities.Billing.PlanExtra", "PlanExtra")
                        .WithMany()
                        .HasForeignKey("PlanExtraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_orders_plan_extras_plan_extra_id");

                    b.Navigation("Order");

                    b.Navigation("PlanExtra");
                });

            modelBuilder.Entity("Core.Entities.Course.Exercise", b =>
                {
                    b.HasOne("Core.Entities.Course.Workout", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercises_workouts_workout_id");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Core.Entities.Course.ExerciseMetric", b =>
                {
                    b.HasOne("Core.Entities.Course.Exercise", "Exercise")
                        .WithMany("Metrics")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_metrics_exercises_exercise_id");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Core.Entities.Course.Lesson", b =>
                {
                    b.HasOne("Core.Entities.Course.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Core.Entities.Course.Workout", b =>
                {
                    b.HasOne("Core.Entities.Course.Course", "Course")
                        .WithMany("Workouts")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workouts_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.DailyMenu", b =>
                {
                    b.HasOne("Core.Entities.FoodEntites.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_menus_foods_food_id");

                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_menus_users_user_id");

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.Food", b =>
                {
                    b.HasOne("Core.Entities.FoodEntites.FoodCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_foods_food_categories_category_id");

                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_foods_users_user_id");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.FoodMetrics", b =>
                {
                    b.HasOne("Core.Entities.FoodEntites.Food", "Food")
                        .WithMany("Metrics")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_food_metrics_foods_food_id");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Core.Entities.Notification.Notification", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Notification.Reminder", b =>
                {
                    b.HasOne("Core.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reminders_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodUserExtra", b =>
                {
                    b.HasOne("Core.Entities.FoodEntites.Food", null)
                        .WithMany()
                        .HasForeignKey("FavouriteFoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_food_user_extra_foods_favourite_foods_id");

                    b.HasOne("Core.Entities.Auth.UserExtra", null)
                        .WithMany()
                        .HasForeignKey("UserExtraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_food_user_extra_user_extras_user_extra_id");
                });

            modelBuilder.Entity("Core.Entities.Auth.User", b =>
                {
                    b.Navigation("Extra");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Core.Entities.Course.Course", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("Core.Entities.Course.Exercise", b =>
                {
                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("Core.Entities.Course.Workout", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Core.Entities.FoodEntites.Food", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
