namespace WebApi;

/// <summary>
/// Idempotent DDL that guarantees the CRM (AddCrmPipeline) schema exists, even when the
/// EF migration history claims it was applied but the columns/tables drifted away.
/// Runs on startup after <c>Database.Migrate()</c>; every statement is a no-op when the
/// object already exists, so it is safe to run on every boot.
/// </summary>
public static class CrmSchemaGuard
{
    public const string EnsureSql = """
        ALTER TABLE leads
            ADD COLUMN IF NOT EXISTS app_open_count bigint NOT NULL DEFAULT 0,
            ADD COLUMN IF NOT EXISTS created_at timestamp without time zone NOT NULL DEFAULT now(),
            ADD COLUMN IF NOT EXISTS food_tracked_count bigint NOT NULL DEFAULT 0,
            ADD COLUMN IF NOT EXISTS last_contacted_at timestamp without time zone,
            ADD COLUMN IF NOT EXISTS lost_at timestamp without time zone,
            ADD COLUMN IF NOT EXISTS lost_reason character varying(300),
            ADD COLUMN IF NOT EXISTS next_follow_up_at timestamp without time zone,
            ADD COLUMN IF NOT EXISTS operator_id bigint,
            ADD COLUMN IF NOT EXISTS payment_provider integer,
            ADD COLUMN IF NOT EXISTS score integer NOT NULL DEFAULT 0,
            ADD COLUMN IF NOT EXISTS status integer NOT NULL DEFAULT 0,
            ADD COLUMN IF NOT EXISTS temperature integer NOT NULL DEFAULT 0,
            ADD COLUMN IF NOT EXISTS water_tracked_count bigint NOT NULL DEFAULT 0,
            ADD COLUMN IF NOT EXISTS won_amount bigint,
            ADD COLUMN IF NOT EXISTS won_at timestamp without time zone,
            ADD COLUMN IF NOT EXISTS workout_started_count bigint NOT NULL DEFAULT 0;

        CREATE TABLE IF NOT EXISTS follow_ups (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            lead_id bigint NOT NULL,
            operator_id bigint NOT NULL,
            due_at timestamp without time zone NOT NULL,
            note character varying(500),
            is_done boolean NOT NULL DEFAULT false,
            done_at timestamp without time zone,
            escalated boolean NOT NULL DEFAULT false,
            created_at timestamp without time zone NOT NULL DEFAULT now()
        );

        CREATE TABLE IF NOT EXISTS lead_activities (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            lead_id bigint NOT NULL,
            actor_id bigint,
            type integer NOT NULL,
            description character varying(500) NOT NULL,
            created_at timestamp without time zone NOT NULL DEFAULT now()
        );

        CREATE INDEX IF NOT EXISTS ix_leads_operator_id ON leads (operator_id);
        CREATE INDEX IF NOT EXISTS ix_leads_status ON leads (status);
        CREATE INDEX IF NOT EXISTS ix_leads_score ON leads (score);
        CREATE INDEX IF NOT EXISTS ix_leads_next_follow_up_at ON leads (next_follow_up_at);
        CREATE INDEX IF NOT EXISTS ix_follow_ups_lead_id ON follow_ups (lead_id);
        CREATE INDEX IF NOT EXISTS ix_follow_ups_operator_id ON follow_ups (operator_id);
        CREATE INDEX IF NOT EXISTS ix_follow_ups_due_at ON follow_ups (due_at);
        CREATE INDEX IF NOT EXISTS ix_follow_ups_is_done ON follow_ups (is_done);
        CREATE INDEX IF NOT EXISTS ix_lead_activities_lead_id ON lead_activities (lead_id);
        CREATE INDEX IF NOT EXISTS ix_lead_activities_actor_id ON lead_activities (actor_id);

        -- Legacy rows backfilled with 0 are invalid enum values (status/temperature start at 1)
        -- and break JSON enum serialization. Normalise them to New / Cold (unassigned).
        UPDATE leads SET status = 1 WHERE status = 0;
        UPDATE leads SET temperature = 1 WHERE temperature = 0;
        """;
}
